### ISSUE TITLE
About setupContainer

### ISSUE THREAD

**Issue by yubozhao** [vesper-framework/vesper#1]
First, Great work. I really believe node/typescript need this kind of framework to provide best practice and help speed up development.

Question about setupContainer.

In your sample: authorization & subscription.  Both use setupContainer.  Does it make sense to make setupContainer as an array instead?

**Comment by pleerock** [comment]
No, I don't see why it should be an array, its just a function where you setup request-based container.

**Comment by yubozhao** [comment]
Oops, didn't see your response before I submit a [PR](https://github.com/vesper-framework/vesper/pull/2) 

I am just wondering if I want to use setupContainer for both use cases in sample 10 &11. I would write them in the same setupContainer function, right?

```typescript
{
  setupContainer: async (container, action) => {
  	//sample 10 current user
	const user = await getRepository(User).findOneOrFail(action.request.query.id);
    const currentUser = new CurrentUser();
	container.set(CurrentUser, currentUser);

    //sample 11 subscription
    container.set(Pubsub, pubsub);
  },
}
```

**Comment by pleerock** [comment]
@yubozhao correct, its just a function where you can write any value into the container and then use it anywhere in your app. I'll close the PR, thanks for the efforts
