### ISSUE TITLE
Query runner already released. Cannot run queries anymore.

### ISSUE THREAD

**Issue by josephktcheung** [vesper-framework/vesper#10]
I'm using postgres in vesper's typescript-advanced-example. I got this `Query runner already released. Cannot run queries anymore.` error if I run a mutation and retrieve `categoryNames` like this:
```gql
mutation PostSave {
  postSave(title: "lol", text: "lol2", categoryIds: [1]) {
    id
    categories {
      id
      name
    }
    categoryNames
  }
}
```  
It works fine if I use sqlite. No idea why this happens. Perhaps it's a typeorm's bug?

**Comment by josephktcheung** [comment]
Here's reproduction branch https://github.com/josephktcheung/typescript-advanced-example/tree/feature/postgres

**Comment by josephktcheung** [comment]
I believe the reason is that resolvers is reusing the `entityManager` in container instance which is actually a `transactionalEntityManager`. Since the mutation action is executed and returned, the `transactionalEntityManager` is released. However the container instance still uses the released `transactionEntityManager` and `transactionalEntityManager` is injected to the resolver.

If I change [`executeResolver`](https://github.com/vesper-framework/vesper/blob/35234c429a1dc64a0a30599923022f3e4ce50e85/src/ActionExecutor.ts#L37) in `ActionExecutor` to run [`step1`](https://github.com/vesper-framework/vesper/blob/35234c429a1dc64a0a30599923022f3e4ce50e85/src/ActionExecutor.ts#L47) instead of `step3`, the resolver works but I guess it's not ideal because it will be run multiple times if there are multiple resolvers.

**Comment by josephktcheung** [comment]
@pleerock saw your commits. could you release a new version? Thanks!

**Comment by pleerock** [comment]
Done in 0.1.3
