### ISSUE TITLE
A few questions / ideas

### ISSUE THREAD

**Issue by alidcastano** [vesper-framework/vesper#14]
- Why do controllers and resolvers need to be defined in separate files? I feel like with Graphql, the resolver pattern is all that is needed, and I'm not sure why the distinction needs to be made.
- I started my own Express setup before seeing Vesper, and I'm autoloading my `entities`, `typeDefs` and `resolvers` based on file naming conventions. Is this something that you'd be interested in doing with Vesper? (I know Typeorm already allows this for entities.)
- How risky would you say it'd be to use Vesper at this stage of the project? 
- Have you looked into Prisma? It auto generates CRUD operations based on graphql models. Is this something you'd be interested in doing with Vesper?

**Comment by yubozhao** [comment]
Just my opinion on the first question.  

The resolver are there for the fields you need a customized answer or the field that doesn't exist on your entity. 

For example, on your entity ```POST``` you have field blogs(OneToMany with ```BLOG```) on your GraphQL type, you have one field called ```blogNames: [String]```.  You want to use the resolver for ```blogName```, since it doesnt exist on your entity.

**Comment by alidcastano** [comment]
I understand the difference, I just feel that schema stiching would be done better via decorators and you can define all the logic in each entities respective resolver.

Leave controllers for REST APIs :)

**Comment by 19majkel94** [comment]
> distinction is made by graphql itself

Technically it's incorrect. `Query` and `Mutation` are just normal `GraphQLObjectType` and `getUser` query or `editProject` mutation are just fields of that object type. The only difference is when we attach this "special" object types to schema, so multiple mutations are resolved sequentially while queries - parallel.

**Comment by alidcastano** [comment]
I didn't say that typeorm enforces conventions. What I mean is that you can load entities based on configured path, e.g.  `{ entities: ['./src/**/entity{.ts,.js}'] }`.

And ah, to be clear, I've specifically been using Apollo Graphql, which generates a schema based on typedefs and resolvers: https://www.apollographql.com/docs/graphql-tools/generate-schema.html

Nest.js also works similarly https://docs.nestjs.com/graphql/resolvers-map

But anyway, I'll go ahead and close this, thanks

**Comment by pleerock** [comment]
> What I mean is that you can load entities based on configured path

you can load controllers, resolvers and schemas based on paths as well.
