### ISSUE TITLE
Config (like api keys, password salts, analytic keys, etc)

### ISSUE THREAD

**Issue by joshstrange** [vesper-framework/vesper#17]
I see in the project structure there is a config.json mentioned but the sample projects don't implement them and I can't see docs about it. Where is the best place to store keys that shouldn't be in a repo and/or should change per-environment?

**Comment by pleerock** [comment]
you can define "config.json" in root if your project (near package.json) and it will read all data from it and put all values inside container. For example:

`config.json`:

```json
{
  "token": "abc-test"
}
```

Then you can get it via `Container.get("token")` or `constructor(@Inject("token") token: string) {` in your app.
