### ISSUE TITLE
TypeError: Cannot read property 'isTransactionActive' of undefined

### ISSUE THREAD

**Issue by leoregul** [vesper-framework/vesper#18]
Hello
At first, thanks for your great framework!

With version 0.1.5 was noticed this issue:
TypeError: Cannot read property 'isTransactionActive' of undefined
  at apollo_server_core_1.runHttpQuery.then.then.catch (...\node_modules\vesper\index.js:111:54)
  at <anonymous>
  at process._tickCallback (internal/process/next_tick.js:188:7)

Driver: 'sqljs'

I suppose, 'transactionEntityManager.queryRunner !== undefined &&' is missed.

And, could you update package typeorm in 'dependencies'?

**Comment by pleerock** [comment]
fixed in 0.1.7
