### ISSUE TITLE
Custom Scalar

### ISSUE THREAD

**Issue by jvbianchi** [vesper-framework/vesper#4]
How can I add some custom Scalar like Date, Time, JSON and Enum?

**Comment by jvbianchi** [comment]
I tried to follow this [tutorial](https://github.com/apollographql/graphql-tools/blob/master/docs/source/scalars.md) but I could not make it work with this framework.

**Comment by pleerock** [comment]
There are two options in `bootstrap` you can use:

```ts
bootstrap({ 

     customResolvers: {
          /// ... your resolvers
     },
     customTypeDefs: {
          /// ... your type defs (scalars and others)
     }
});

**Comment by jvbianchi** [comment]
I'm trying to useit like this:

```typescript
import { GraphQLDate, GraphQLTime, GraphQLDateTime } from 'graphql-iso-date';

bootstrap({ 
       customTypeDefs: [GraphQLDate, GraphQLTime, GraphQLDateTime],
});
```
but I got this error: 
```
GraphQLError: Syntax Error GraphQL request (37:1) Unexpected Name "Date"

36:
37: Date,Time,DateTime
    ^
```

**Comment by pleerock** [comment]
No, sorry I copy/pasted that block, actually `customTypeDefs` accepts a string, e.g. `customTypeDefs: "GraphQLDate \r\n GraphQLTime \r\n GraphQLDateTime"

**Comment by jvbianchi** [comment]
Finally I could make it work, final code:
```typescript
bootstrap({
  customResolvers: {
    Date: GraphQLDate,
    Time: GraphQLTime,
    DateTime: GraphQLDateTime,
  },
})
```

**Comment by gregwym** [comment]
Thanks to @jvbianchi , I got mine working. I also got https://github.com/taion/graphql-type-json work in the same way except I have to declare `scalar JSON` in graphql as well. Not sure why `graphql-iso-date` does not require that.
