### ISSUE TITLE
Custom connection options

### ISSUE THREAD

**Issue by josephktcheung** [vesper-framework/vesper#6]
Hi,

This is a nice framework, thank you for creating this!

I have 2 questions on customising the TypeORM connection options:
1. Can we have multiple database connections in 1 project? Currently it only connects to 1 database.
2. Would we be able to connect TypeORM by ourselves instead of being handled by the framework?

Best,
Joseph

**Comment by josephktcheung** [comment]
More details on point 2, I tried to deploy vesper onto AWS lambda but failed because of [this issue](https://github.com/typeorm/typeorm/issues/1575). Since connection logic is buried inside the `SchemaBuilder`, there's no way for me to set connection by myself e.g. doing what @pleerock suggests in the issue:
```ts
async function createAwsConnection(): Promise<Connection> {
    const options = await new ConnectionOptionsReader({ root: "/path/to/orm-config/directory" }).get("default");
    return getConnectionManager().create(options).connect();
}
```

**Comment by parano** [comment]
@josephktcheung for 1, I believe you can actually do it by modifying the ormconfig file, see  http://typeorm.io/#/using-ormconfig

**Comment by josephktcheung** [comment]
Hi @parano, thank you for replying!

Actually putting multiple connections in ormconfig doesn't work. Here's my `ormconfig.js`:

```
module.exports = [{
  "type": "postgres",
  "host": process.env.DB_HOST,
  "port": process.env.DB_PORT,
  "username": process.env.DB_USERNAME,
  "password": process.env.DB_PASSWORD,
  "database": process.env.DB_NAME,
  "schema": process.env.DB_SCHEMA,
  "cli": {
    "migrationsDir": "src/migration"
  }
},
{
  "name": "db2",
  "type": "postgres",
  "host": "localhost",
  "port": 1201,
  "username": "test",
  "password": "test",
  "database": "test",
  "schema": "test",
  "cli": {
    "migrationsDir": "src/migration"
  }
}];
```

And this is how I initialise vesper in `index.ts`:
```ts
import { bootstrap } from 'vesper';
import { getConnection } from 'typeorm';

bootstrap({
  port: 3000,
  schemas: [`${__dirname}/schema/**/*.graphql`],
}).then(() => {
  const defaultConnection = getConnection();
  console.log('default', defaultConnection);

  const db2Connection = getConnection('db2');
  console.log('db2', db2Connection);
});
```
When you run `index.ts`, it can successfully log the `defaultConnection` but throws `ConnectionNotFoundError: Connection "db2" was not found.` when `getConnection('db2')` is run.

It's because again internally, vesper runs TypeORM's `createConnection` which only create a single connection in [`SchemaBuilder`](https://github.com/vesper-framework/vesper/blob/15c94f542eb371749436e6c9360ca1b401c79dd5/src/SchemaBuilder.ts#L191). If we want to connect to multiple databases, we need to use TypeORM's [`createConnections`](http://typeorm.io/#/multiple-connections) instead. Also from TypeORM, if `createConnection` is called without any parameter, [only one connection from ormconfig will be created (name "default" or connection without name).](https://github.com/typeorm/typeorm/blob/9be7e40e29cbef2024445c9132fb665faf696fde/src/index.ts#L175-L179)

So that's why I ask if we can create connections by ourselves because currently vesper is putting constraints on the way database(s) is connected. My pull request is just a hot fix for point 2, ideally we should not [hardcode the connection to always get the `default` one](https://github.com/vesper-framework/vesper/blob/15c94f542eb371749436e6c9360ca1b401c79dd5/src/SchemaBuilder.ts#L169-L171). What if I don't like the name `default` and want to rename it to something more meaningful internally?

I'm not sure how much changes will be needed for vesper to fully support multiple connections to multiple databases, but I believe it's needed if vesper wants to appeal to a broader audience.

Thanks,
Joseph

**Comment by pleerock** [comment]
You'll be able to use multiple connections but you'll loose some of "automatic functionality" and its unlikely possible to support them and have all those perks. If you want details go through the code and take a look how things are organized and I'll explain what issues we have with multiple connections.
